add `writeValueWithoutResponse` and `writeValueWithResponse` methods
chrvadala/node-ble pull request #47
Opened 2022-10-31 18:41 UTC by derwehr

The [WebBluetooth specs](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue) deprecated `writeValue()`. So I added `writeValueWithoutResponse` and `writeValueWithResponse` to be back on par with the spec

2022-11-02 08:09 UTC, chrvadala requested changes
Hello @derwehr, thanks for this PR. I would like to merge as soon as possibile, but before that, I need that you add some unit tests on these functions.
Can you do that? 
Thanks for your contribution

2022-11-02 08:49 UTC, derwehr commented
Hi @chrvadala, thanks for the quick reply. I have now added tests.

2022-11-02 23:23 UTC, chrvadala approved these changes

2022-11-02 23:24 UTC, chrvadala commented
Thanks @derwehr, I will merge and publish in a couple days. Thanks a lot

2022-11-12 17:22 UTC, merged

2022-11-12 17:44 UTC, chrvadala commented
I released this PR with 1.9.0 and I added your name into contributions list.
Thanks @derwehr for your help