Add function for get ManufacturerData and AdvertisingData
chrvadala/node-ble pull request #53
Opened 2023-02-03 13:33 UTC by Raffone17

Add function  for get ManufacturerData and AdvertisingData to the Device Interface.

2023-02-04 08:33 UTC, chrvadala requested changes
Hello, thanks for this useful PR. Can you integrate it with some unit tests. 
Thank you very much

2023-06-28 10:51 UTC, lesleyxyz commented
Looks like it has the required unit tests, are you ok with the changes @chrvadala ?

2023-09-22 07:23 UTC, Raffone17 commented
@chrvadala I integrated some unit tests, any news?

2023-10-16 10:23 UTC, gmacario commented
> @chrvadala I integrated some unit tests, any news?

Hello @chrvadala,

Any chances that either this PR or #61 get reviewed and possibly merged?

Thanks,
Gianpaolo

2024-02-13 15:12 UTC, chrvadala requested changes

2024-02-13 15:12 UTC, chrvadala commented on src/Adapter.js
>      })
is this part related to the current PR? It seems that belongs to a different feature

2024-02-13 15:12 UTC, chrvadala commented on src/Device.js
> +      }
I understand that you want to proxy the Manufacturer change event to the Device event handler, but currently this isn't available for the rest of props. I prefer to be consistent in the project and remove this part for now.

2024-02-13 15:12 UTC, chrvadala commented on src/index.d.ts
> +        startDiscovery(options?: {transport?: string, duplicateData?: boolean}): Promise<void>;
is this needed by the current PR?

2024-02-14 11:47 UTC, chrvadala commented
Superseed by #61

2024-02-14 11:47 UTC, closed without merging

2024-05-19 20:39 UTC, chrvadala commented
Released with 1.11