Fix memory leak in waitDevice method
chrvadala/node-ble pull request #75
Opened 2024-09-17 08:58 UTC by Raffone17

In the waitDevice method, if the device is not found the 'operation timed out' error is thrown but the interval is not cleared. I added a try and finally statements for avoid this problem.

2024-10-15 14:55 UTC, gmacario commented
Hello @chrvadala,

Please let us know when you plan to have a look at this PR by @Raffone17. Thank you!

2024-10-16 05:57 UTC, chrvadala commented
Thanks for this PR guys, can you integrate it with a test?
I see that the fix makes completely sense, but it is better to cover this case with a test.
You can mock `getDevice` for that. It seems the easier solution

2024-10-16 09:55 UTC, Raffone17 commented
Hello @chrvadala,
I did a unit test that covers the scenario.

2024-10-18 17:56 UTC, chrvadala requested changes
Thanks for adding a test. I added few comments inline.

2024-10-18 17:56 UTC, chrvadala commented on test/Adapter.spec.js
> +    const spyClearTimeout = jest.spyOn(global, 'clearInterval')
I think that there's a mistake on this line.

2024-10-18 17:56 UTC, chrvadala commented on test/Adapter.spec.js
> +    jest.useFakeTimers('legacy')
Is there a specific reason for using the legacy implementation?

2024-10-18 17:56 UTC, chrvadala commented on test/Adapter.spec.js
> +    jest.advanceTimersByTime(500)
you can specify here the timeout variable that you declared

```suggestion
    jest.advanceTimersByTime(timeout)
```

2024-11-03 11:47 UTC, chrvadala approved these changes

2024-11-10 17:47 UTC, merged

2024-11-10 19:25 UTC, chrvadala commented
Released with v1.12.0
Thanks @Raffone17 and @gmacario for your help on this project